### PR TITLE
create ja_JP

### PR DESCRIPTION
**Pull request by ghost**
I made ja_JP.lang
There was so much content to translate so I decided to upload part by part

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Awesome, thanks! :)

**Comment by tento64** [comment]
I am also translating into Japanese.
私も日本語に翻訳しています。
こういう被りは初めてなのですが、協力できますか？

**Comment by TheCyberBrick** [comment]
> I am also translating into Japanese.

Nice!
Maybe you @tento64  and @pentantan could work together to complete the translation?

**Comment by ghost** [comment]
Sure!

**Comment by tento64** [comment]
[ja_JP.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/3735829/ja_JP.txt)

Here is my translation.

**Comment by ghost** [comment]
@tento64 
marged tento64's ja_JP.lang!
ja_JP.langをTento64さんのja_JP.langに上書きしました

**Comment by TheCyberBrick** [comment]
Getting close to a release so I'm merging this. If you want to make more changes feel free to create another new PR 👍 
Thanks!

**Comment by TheCyberBrick** [comment]
Ah another thing, if you want your localizations to be released as soon as possible please create them on the 1.12-fixes branch. That branch is released to the public quite a lot more frequently.

**Pull request merged**
