### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by mc-kaishixiaxue**
v3.5.7
If possible, please @RisingInIris2017 check it.

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Thanks! Is this ready to be merged?

**Comment by mc-kaishixiaxue** [comment]
Wait. I have something to change on tomorrow. About config tooltips.

**Comment by mc-kaishixiaxue** [comment]
Now it's time to merge.

**Comment by TheCyberBrick** [comment]
Thank you :)

**Comment by TheCyberBrick** [comment]
In the future please make sure to base your PR for localizations on the 1.12-fixes branch 👍

**Pull request merged**
