### PR TITLE
Fixes and new features

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Awesome, just in time!
Thanks ❤️

**Comment by ghost** [comment]
Draeton's Purge button does not appear in lang file :c

**Comment by GoryMoon** [comment]
@NathanielFreeman Added some missing translations along with fixing the purge button being hardcoded 554e753fc35d663a891d82a37d57eefd89efa746

**Comment by ghost** [comment]
entity.thebetweenlands.chiromaw_hatchling_lightning.name - for lightning chiromaw's egg
it's not in lang file
Is it a mistake or is it correct?

**Comment by GoryMoon** [comment]
Got some fixes and added the missing hatchling name 133b2e92e8d575fb4cf7287336bd5309b1fba6bf

**Pull request merged**
