### PR TITLE
Update zh_cn for dungeon stuffs and sushi

### PR DESCRIPTION
**Pull request by RisingInIris2017**
What a great update!
I have translated nearly all the new items in this update.
Would you dear devs have these translations merged?
Thanks a lot in advance!

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Awesome, thanks!
I'll keep this open for now because some more content will be added for the next update ;)

**Comment by RisingInIris2017** [comment]
I'm waiting for new features :>
And they will get their translations as soon as possible.

**Comment by TheCyberBrick** [comment]
Thanks 👍

**Comment by RisingInIris2017** [comment]
I managed to have new items translated :)

**Comment by RisingInIris2017** [comment]
Finally I got new entries translated! Would you dear devs have these merged?

**Comment by TheCyberBrick** [comment]
Of course :)
The update is taking a bit longer, but hopefully it should be done somewhat soon

**Comment by TheCyberBrick** [comment]
Getting close to a release so I'm merging this. If you want to make more changes feel free to create another new PR 👍 
Thanks!

**Comment by TheCyberBrick** [comment]
Ah another thing, if you want your localizations to be released as soon as possible please create them on the 1.12-fixes branch. That branch is released to the public quite a lot more frequently.

**Comment by RisingInIris2017** [comment]
Oh, thanks a lot for your merging and advice! You kind-hearted brick :)

**Pull request merged**
