### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by Externallex**
Translated ALL achievements, as well as some blocks and items.
The main focus was only on the translation of ALL achievements.

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Hey! Thank you, much appreciated :)
Will be added with the next update.

**Comment by Bytegm** [comment]
> Hey! Thank you, much appreciated :)
> Will be added with the next update
it's been almost 3 months, so are you planning on adding?))

**Comment by Externallex** [comment]
@TheCyberBrick, it's been almost 3 months, so are you planning on adding?))

**Comment by TheCyberBrick** [comment]
Yes. You've update the localization file of our in-dev branch which means it'll be released once our next update is finished. It's taking a bit longer than we've expected

**Comment by TheCyberBrick** [comment]
Getting close to a release so I'm merging this. If you want to make more changes feel free to create another new PR 👍 
Thanks!

**Comment by TheCyberBrick** [comment]
Ah another thing, if you want your localizations to be released as soon as possible please create them on the 1.12-fixes branch. That branch is released to the public quite a lot more frequently.

**Pull request merged**
