### PR TITLE
Menu Lib Support

### PR DESCRIPTION
**Pull request by jredfox**
this will add it to the array list of main menus. if you want to make it a dependency that's up to you but, at least consider this code as it's not required as a dependency with this code.

### CODE REVIEW

**Comment by jredfox** [comment]
what is the error is it a compile error I ran the code didn't error on my screen let me pull it up in eclipse

**Comment by TheCyberBrick** [comment]
Travis broke again, not because of the code.
Is there a specific reason why we need to add this? The way I see it, it would make more sense if you added support for mods in your own code so that you don't depend on other mods adding it. Check if a mod with a main menu is loaded, and if so, show your own main menu by using a GuiOpenEvent listener with lowest priority and `receiveCanceled = true` and changing the GUI with `event.setGui(yourMainMenu)`.

**Comment by jredfox** [comment]
Yes it adds support for ArrayList[ IMenu] and if yours isn't registered it doesn't shows up. *Don't you want your menu showing up in an array list of main menus that you can brows via buttons?* It's all configurable as well and this is all that needs to happen on your side. So you got nothing to loose/worry about no dependencies even.

ArrayList[IMenu]  > IMenu contains data and info to construct guis for the main menu
Event > Replace main menu and set the the current saved index
Your not on the arraylist > IMenu your menu never shows up
This commit > registers your gui to the MenuRegistry.class. 
This is the result in 1.12.2 with registering the gui. You can browse them via the buttons < and > to move pages. 
**I was unable to test this directly with your mod as your src has lots of compile errors that prevented anything from running. So if there is a bug I could fix it later.**

I provide the api not the mod compatibility directly on my mod. This is a **menu registry** if it's not registered in that array the gui won't show up. That would be like saying it's my libs job to register other mods blocks/items. I simply wrote this out for you because your a popular mod and clients requested it specifically. *I made this commit reflection so you don't depend upon anything*

**Comment by TheCyberBrick** [comment]
Yes, I got that part with the menu switching.


>It's all configurable as well and this is all that needs to happen on your side.

>This is a menu registry if it's not registered in that array the gui won't show up. That would be like saying it's my libs job to register other mods blocks/items.

But that's exactly my point. Your mod adds the functionality to switch menus, so wouldn't it make sense if your mod also makes that functionality work with other mods?
Why do we have to add this if you can do it on your side just as well with almost exactly the same code?
It'd be easier for both us and you, because we wouldn't have to maintain anything in case your lib changes and you'd have the freedom to add support for any mod within seconds.

Also, the source code doesn't have any compile errors :P
Make sure the access transformer is applied properly.

**Comment by jredfox** [comment]
Impossible as 100+ mods might want to add their menu and try to replace it. Each mod overrides each other until their is one menu left and that would be random.

ArcticCraft > adds menu
Your mod > adds menu
Bug Mod > adds menu 
event handler calls event on mine > most I could do is check if last menu that I can see is registered and if not add it
Orespawn > adds menu
Twilight forest > adds menu
event handler post menu lib > replaces main menu at event handler lowest > everything gets overriden

Eclipse and jvm runtime said it had compile errors please check your current source. I forgot to add the jvm arg for coremod but, eclipse said it had lots of errors still. pull it up and check for yourself

**Comment by TheCyberBrick** [comment]
What stops you from listening to `GuiOpenEvent` and then displaying the menu your mod wants to display?

**Comment by jredfox** [comment]
question do you or do you not want your menu to show up when browsing menus with my mod? Nothing is stopping me your menu isn't registered so if it's not registered it an't going to show up

The issue isn't your mod is overriding mine the issue is your menu isn't registered to my array so it will never show up even when browsing. This commit fixes that.

I don't know how I am not clear on this? The lib adds an array of browseable menus but, they have to be registered from the mod trying to add the menu in. Saves the current index the menu is on and a configurable order for the menus pages to be in.

**Comment by TheCyberBrick** [comment]
I appreciate your effort and the PR, but I just can't quite see how this is a better solution than doing it on your side. It's easier for both sides involved.

>Nothing is stopping me

Then why don't you register our menu in your mod and use `GuiOpenEvent` to replace the menu with yours?

**Comment by jredfox** [comment]
How am I not clear? 

Forge Registries don't register block not going to be added
My Menu Lib Same concept how is this not clear to you?
 
I don't register your menu as 400 mods might in the future add them this is a fix for your side to register it. *Not a libraries job to register other mods objects proper fix occurs on mods side to ensure no unexpected errors occur*. There is no forge register for main menus so I created one It needs to happen on the mods side to register it in order for compatibility to occur.

"I appreciate your effort and the PR, but I just can't quite see how this is a better solution than doing it on your side. It's easier for both sides involved."

Code is already written on your side you have it easy. So I don't see how it's more difficult for me to register your object to my array. Things could easily break in the future on my side if you don't do it on yours.

**Comment by TheCyberBrick** [comment]
Why do you assume I didn't understand? I've explained why this doesn't make much sense to me.

>Forge Registries don't register block not going to be added
My Menu Lib Same concept how is this not clear to you?

Your mod is not Forge, so how is this even comparable? It is your mod that adds this so I don't see any reason why you wouldn't also register menus yourself using reflection.

Oh and, that condescending tone surely is going to help 👍

**Comment by jredfox** [comment]
I was giving an example of a registry and arrays since I "apparently wasn't clear".

I gave multiple examples of what the menu lib does. You choose whether or not to implement it.

I saw class.forname several dozens places in your code so I don't know why you can't accept 3 more lines that only occur when my mod is loaded.

I have done my best explaining myself. Easy on your end to add this commit and add compatibility. If you have any more questions on what it is let me know.

**Comment by TheCyberBrick** [comment]
>I saw class.forname several dozens places in your code so I don't know why you can't accept 3 more lines.

Haha thanks for the good laugh, now please show me where :)

**Comment by TheCyberBrick** [comment]
>ArcticCraft > adds menu
Your mod > adds menu
Bug Mod > adds menu
event handler calls event on mine > most I could do is check if last menu that I can see is registered and if not add it
Orespawn > adds menu
Twilight forest > adds menu
event handler post menu lib > replaces main menu at event handler lowest > everything gets overriden

Yes I do get that. But you can use reflection to check if another mod's main menu class is loaded and if so register it as menu...

**Comment by jredfox** [comment]
I am a lib not a hard coded application bridge between 80 popular mods. That's a job for another mod. 

I remember seeing it Class.forName() in your code alot during 1.7.10 for reflection in your mod can't recall what build it was alpha and you were checking things with shaders? and a couple other mods/things. 

by the way I made this for mods like your's and the aetherii. When I remember menus were constantly getting overridden by each other. Aetherii had an api for that but, it was poorly coded so nobody used it plus it got overridden by other menus. I re-wrote it from scratch same idea but, coded way better. Better interface that makes sense and easy registry. And best of all no bugs with it unlike the aetherii's original menu.(no random crashes from clicking the button too fast). *So when my client asked me to add support I remembered this mod again.*

**Comment by jredfox** [comment]
if your concerned about what the method does you can veiw it's source here:
https://github.com/jredfox/evilnotchlib

I think I addressed all of your concerns if you have any further questions you can go to evil notch lib curseforge from their either comment or join discord. 

You choose to add it or not tried my best thanks for your time. My client(s) are hoping you add *these three lines*. 👍

**Comment by vadis365** [comment]
Hello,
Support for other mods SHOULD be optional to this lib and adding mod support is on the side of the lib to implement, it is the ONLY acceptable way people will use it. The excuse of not being able to do it is a poor one and shows a complete lack of effort - make your mod work with other mods DO NOT try and make other mods do the work. As for the the idea that our coding team need to have things explained to them in an obviously condescending way is quite frankly insulting, rude and not the way to make friends. TheCyberBrick has explained clearly and in a concise way how you COULD make your mod not so much of a hacky-shoe-horn mod but you refuse to accept the information supplied from one of the most talented modders myself and many others are acquainted with. All I can suggest is that we add that your mod is not compatible with the BL on our downloads page until you write a mod that provides a better implementation.
On a side note, The BL SRC is fine and has no issues with compiling for me atm - maybe the lack of understanding appears on the wrong side this convo.
Cheers,
Me.

**Comment by jredfox** [comment]
yeah and I could add support for 400+ mods if I felt like it not going to. If mods decide not to add it I consider it they don't want the menu in the first place which is always a right assumption if they are away of my mod.

If you don't want the menu added this pull will be closed if you do want it added this pull will get integrated. **It has nothing to do with my effort @vadis365**  *this is do you want your menu showing up for my lib as a boolean* not O I should find every single freaken mod that adds a menu and hard code everything so I can have 20+ crashes not happening.

@vadis365 this was already explained before it's impossible to auto detect all the menus that are trying to override the main menu as it's an event no arraylists nothing just say replace this gui at this specific event with this. The only way is to have a registry. Also calling my mod hackish is a great complement that's what I was going for hack forge into doing what ever I want when I want and to do it the way I want. So I can call one line per object and be done with it. I wasn't being rude but, cyberbrick kept making me repeat myself.

I agree with the chimp on one thing it's optional. If you choose not to add it it won't show  up not my choice it's the modders and that is proper modding letting the modder choose to register stuff. *Not me forcing your mod to register a menu when you might not want it.* Especially if you close this pull without integrating the three lines. 

This is my last comment here do what you want. Not my job to force register other peoples menus it's the modders. At this point I don't care. Just don't come bother me when alot of clients bothering you wondering why it's not working. Basically by denying this pull to me means you don't want your main menu.

never in my life have I seen 3+ people talk about 3 lines of code for 5+hours.  This isn't my issue it shouldn't happen on my side it's not a lack of effort there are no definitions I made one if you don't use it then it's your choice

**that's what I was getting at all along it's not my choice for you to add something from your mod to a registry. It's your choice therefore it has to happen on your side.**

**Comment by vadis365** [comment]
Hello,
The reason the mod and the code are being discussed in this detail is the fact you don't seem to be able to see past your own mod's flaws. It is a bad implementation of a flawed system that offers very little incentive for anyone to use and opting not to use it then causes issues. Your idea is a good one but the implementation is not useful and I can see other big mods choosing to ignore and not use this, if not for the fact it's badly implemented, for the fact you seem to have a fundamental problem with the idea that other people actually know more than you and have tried to be helpful in steering you in to a better approach. I have Spoken to both the Twilight Forest team and Aether about this - neither of which seem interested in this and I'm sure the Tropicraft mod will see the problem too. 
You can be as forthright in your idea as you like and push for things to be done, but also you should be able to take critique.
Cheers,
Me.

**Comment by jredfox** [comment]
chimp there is nothing flawed about evil notch lib there is plenty with forge. forge choose not to have a registry for the main menus take it up with them.

And again not my mods issue it's yours whether or not you try and register it with or without reflection. without would mean a new dependency. 

how the heck is it my mods issue that you don't register something? I am so freaken done here. I add a new system that allows for multiple menus that forge won't support put in 3 lines for you to add and refuse to use it lolz. Even atomic stryker added support for dungeon tweeks because I told him it supported nbt and forge's did not. Added 2 lines of reflection and now  it's compatible you should take his advice that has twice the dls of this mod at least and do it.

look at the source it's not flawed and bug free for the releases

**Comment by TripleHeadedSheep** [comment]
Shit, I ran out of popcorn

**Comment by vadis365** [comment]
Hello,
Thanks. Dl's mean nothing in the grand scheme of things, I mean, if you want to play like that - and remember, I'm just one member of the BL team that includes several well know modders.
It's just numbers.

dl s

I guess we are done here, sorry we couldn't be of any help to you.
Cheers,
Me.

**Comment by Tamaized** [comment]
Twilight Forest doesn't add a menu... Lol

Even if we did we wouldn't soft dep on YOUR mod just to make your system work. That's insane.

**Comment by LatvianModder** [comment]
On behalf of entire modding community - please don't ever make mods again, jredfox, thanks.

**Comment by Wyn-Price** [comment]
You shouldn't do a PR on someone else's mod if you know you can solve the issue yourself. Like many people have said, you shouldn't go through every mod adding soft dep just to make it work. The best solution would be [this](https://github.com/Angry-Pixel/The-Betweenlands/pull/579#issuecomment-382285498), but if you're so against that (which I don't know why you would be) then just add a config with a String array for the classnames of the guis you want to include. There are plenty of ways you can do this without making PRs to all the mods (or 400+ as you say), that's just insane. 
> there is nothing flawed about evil notch lib there is plenty with forge.

There is most definitely stuff wrong with evil notch lib. I spent less a few minutes looking around "evil notch lib" and found multiple things wrong. Firstly, in your [BlockAPI.java](https://github.com/jredfox/evilnotchlib/blob/caf782aa7da35aa105fd7f6992c7041b44943619/src/main/java/com/EvilNotch/lib/Api/BlockApi.java), you are trying to set/get the blocks hardness, soundtype, harvestLevel, stuff like that from the field. This will not always work. There are getter methods in the Block Class that override the getter for just the field. If a mod overrides them, and doesn't set the field value, your mod will break and get the wrong thing. Before you say how a mod should do that to make it compatible with your mod. No. That's not how it should work. You can't make a flawed system then complain when other mods don't change THEIR system to fit with YOUR broken system. When SecretRoomsMod didn't work with CTM, I didn't make a PR to rewrite CTMs baked quad stuff, I just changed my system to make it work with CTM, and that's something you should be doing. Rather than make a broken system and get other mods to work with it, make a working system that has no trouble with other mods.

Another issue I have is your [BasicModel.java](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/minecraft/content/client/models/BasicModel.java). From what it looks like, you're trying to change the texture of the model. This. Will. Not. Work. The texture of the quad that's being rendered is not held in the IBakedModels sprite, its held in the vertex data of each BakedQuad in the list. If you want to retexture a model, just use BakedQuadRetextured on all the quads.

Your [FakeWorld.java](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/minecraft/content/FakeWorld.java) is not very threadsafe. You're caching the entities into static maps. Please read [HERE](https://www.journaldev.com/1061/thread-safety-in-java) and actually get to understand thread saftey, because you clearly don't have any idea of what it means. You are literally storing every entity in the main thread fake world. You're caching entities to your fake world only when the first `WorldEvent.Load` is fired. You do understand that every dimension is its own world class. And that on a server, there will be multiple worlds. You can't just set a static field to the world that's first called in `WorldEvent.Load`.

Another thing wrong with your lib, is that [it is inside iteself](https://github.com/jredfox/evilnotchlib/tree/4c88d2b97fe102f498611ce4e3de2fe65a5b567d/src/main/java/com/EvilNotch/lib/util/src/main/java/com/EvilNotch/lib). I get this is probably a mistake. but accidentally copying your workspace into itself, then going online to brag about how your mod `[has] nothing flawed` are not things that add up.

Finally, there is no reason that your [build.gradle Lines 14-16](https://github.com/jredfox/evilnotchlib/blob/master/build.gradle#L14-L16)
should be like this:
```gradle
version = "1.0"
group = "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"
```
You should definitely change that, ~~most~~ all mod tutorials tell you to change that. It's just dumb to have to manually change the file name each time.

Apart from the amount of empty files. ([here](https://github.com/jredfox/EvilNotchCore/blob/master/src/main/java/com/EvilNotch/Core/asm/CoreModLoader.java) and [here](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/Api/NBTPathApi.java) are the ones i could be bothered to find), and the fact you've used your own `.gitignore`, meaning its much more difficult for people to set up their own PR's, or even load your code into a workspace, evil notch lib isnt that good. The intent behind it look like good, and you have some promising ideas, but it's obvious from looking through your code that its a bunch of tutorials and copypaste mixed into one unholy mess.

I'm not trying to make you feel bad about your code, sure if you look through my code, you'll probably find things that are pretty bad and could be improved (especially with srm), but I understand that my code isn't the best, and I certainly don't brag about how it is flawless, when it clearly isn't. I can also take criticism well, and from what I've read so far from this PR you can't. Someone saying your code isn't bad is not something to be offended about. As cringy as it sounds, you should use the criticism to help yourself get better, not just make yourself look more childish. Your tone throughout this whole PR has been condescending. You have to remember, you are not doing TheCyberBrick or "chimp" a favour by doing this. Noone was going to them asking for support for your mod. You decided to make a PR to THEIR mod to change THEIR code. You have to impress them and try and make them pull, not just think that because you have a mod with 3,375 (at the time of writing this) that you feel the need to try and one up them. I'm not trying to make you feel bad with this, Im just trying to explain that evilnotchlib is not as perfect as you assume it to be, and neither are you. I think you've just fallen a victim to the Dunning-Kruger effect.

image
Also, aren't you the guy that came onto the moddingmc discord, complaining that you want to do model stuff without using jsons. Told everyone that `once a mod is compiled the resources of jsons would be located in the jar if the application closes in the middle of it the jar could corrupt`, something you obviously don't understand yourself, because that is wrong on so many levels. You thought that `IBakedModel#getSprite` was what's rendered, even though you were told countless times (by me and other people) that the real texture is in the vertex data, then to ask if we're all sure that that's how it is. (It is like that). You then say `because I am coding a library if I decide to make a mod that adds 10,000 randomized blocks using my lib into the game with random properties I don't want the game taking a minuet extra parsing the jsons`. When you were told countless times to just use BASIC python to create all the models and stuff you say you `want to do it the hard way`. When everyone was telling you that you were doing it wrong, you go
> so none of you all gave me any straight answers and constricted each other I assume you have never done a custom model before

to the whole group You then try and be condescending and go `ok sorry`, then after litral seconds asking that same person to solve your xy problem. You then left for a couple of hours, came back, asked the exact same question again, got called to `stop being stupid`,  pinged the mods because you got called stupid, the mods told you to fuck off, you then told the mods that people were you stupid, mods told you to stop pinging them and to act normal, then to say `I came here to code not be harassed by someone how doesn't even know that much code.` (You seems to follow that condescending theme). You then tell people their wrong as `you all use an api for recipes IRecipe` and `everything turns into that eventually`, until then leaving. 

If you can’t handle criticism or people better than you telling you you're doing something wrong, don't even bother modding.

**Comment by jredfox** [comment]
pull is still valid should be done on your side but, clients if they know how to locate class names will be able to add support themsleves now I was trying to make it easier on clients. More clients requested this so your welcome

**Pull request closed without merging**
