### PR TITLE
Update ja_JP.lang

### PR DESCRIPTION
**Pull request by tento64**
Updated translations.
Some have not been translated yet.

The translation has been corrected as follows.
ビトウィーンランド→ハザマの地
ウィードウッド→クサノキ
火床の木→暖炉の木
ビトウィーンストーン→ハザマ石
洗浄器→浄化槽

### CODE REVIEW

**Comment by GoryMoon** [comment]
I changed the branch to `1.12-fixes` because it's the one that will get the fixes and releases with the current release.
It's also needed as some changes to the lang files were done recently.

**Comment by tento64** [comment]
I'm sorry, I was a beginner in github and programming, 
so I failed to check the contributing instructions.

**Comment by GoryMoon** [comment]
It's fine, I did it mostly to get it updated to work with the changes I did.

To properly resolve the conflict I think you need to rebase it on to the 1.12-fixes. I see you edited from the web page, don't know it there's a way to do that but I can resolve it before a merge if you want.

Let us know when you feel it's ready for a merge

**Comment by GoryMoon** [comment]
It's fine, I did it mostly to get it updated to work with the changes I did.

To properly resolve the conflict I think you need to rebase it on to the 1.12-fixes. I see you edited from the web page, don't know it there's a way to do that but I can resolve it before a merge if you want.

Let us know when you feel it's ready for a merge

**Comment by tento64** [comment]
Please merge

**Pull request merged**
